
# =====================================================
# Kafka Streams
# =====================================================

quarkus.kafka-streams.application-id=booking-payment-app
quarkus.kafka-streams.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde

quarkus.kafka-streams.bootstrap-servers=my-cluster-kafka-bootstrap-amq-stream.apps.cluster-s6frn.s6frn.sandbox1580.opentlc.com:443

# SSL
quarkus.kafka-streams.security.protocol=SSL

quarkus.kafka-streams.ssl.truststore.location=/Users/sasethi/event-driven-kafka/kafka.truststore.jks
quarkus.kafka-streams.ssl.truststore.password=password

# Optional
quarkus.kafka-streams.topics=booking-topic,payment-topic

# =====================================================
# Camel Kafka
# =====================================================
kafka.bootstrap.servers=my-cluster-kafka-bootstrap-amq-stream.apps.cluster-s6frn.s6frn.sandbox1580.opentlc.com:443
camel.component.kafka.brokers=my-cluster-kafka-bootstrap-amq-stream.apps.cluster-s6frn.s6frn.sandbox1580.opentlc.com:443

camel.component.kafka.security-protocol=SSL
camel.component.kafka.ssl-truststore-location=/Users/sasethi/event-driven-kafka/kafka.truststore.jks
camel.component.kafka.ssl-truststore-password=password

# =====================================================
# Logging
# =====================================================

quarkus.log.category."org.apache.kafka.clients.NetworkClient".level=ERROR